# Generated by Django 5.1.3 on 2024-12-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vodes',
            new_name='votes',
        ),
    ]
